"""In-process loader for the built ssik solver modules (Python 3.11+ only).

The ssik sidecar (``ssik_client`` + ``ssik_sidecar/serve.py``) exists because
Rhino runs CPython 3.9, which cannot import ssik. But the OFFLINE planner runs
in a Python 3.11 venv where ssik installs cleanly -- shelling out to a second
3.11 venv from there is pointless. This module imports the SAME committed
artifact modules (``<arm>_ik.py`` from ``config.get_ssik_artifact_dir()``)
directly into the current interpreter, so a solve is a plain function call.

Extra win over the sidecar: the artifact ``solve()`` supports ``q_seed``
(nearest-branch / trajectory-tracking mode), which the sidecar wire protocol
never exposed. The motion planner leans on this heavily.

This is the ONLY module that touches ``sys.path`` / ``importlib`` for the
artifact modules. Only stdlib + numpy + ``keyframe.config`` are imported here,
so importing this module is always safe -- availability of ssik itself is
probed lazily via :func:`available`.
"""

from __future__ import annotations

import sys
from importlib import import_module
from typing import List, Optional, Tuple

import numpy as np

from husky_assembly_tamp.keyframe import config


# * Lazy caches: the artifact modules (one per arm) and the "can we import ssik
# * at all in this interpreter" probe result. None = not probed yet.
_MODULES: dict = {}
_AVAILABLE: Optional[bool] = None


def available() -> bool:
    """Whether ssik can be imported in the CURRENT interpreter (cached probe).

    Returns:
        bool: True when ``import ssik`` succeeds (a Python 3.11+ env with ssik
        installed), False otherwise (e.g. Rhino's CPython 3.9 -- callers should
        then fall back to the sidecar).
    """
    global _AVAILABLE
    if _AVAILABLE is None:
        try:
            import ssik  # noqa: F401  # probe only; the artifacts import from it
            _AVAILABLE = True
        except ImportError:
            _AVAILABLE = False
    return _AVAILABLE


def _get_module(arm: str):
    """Import (once) and return the built solver module for one arm.

    Args:
        arm (str): "left" or "right" (selects the module via
            ``config.SSIK_ARM_BUILD``).

    Returns:
        module: the imported artifact module (exposes ``solve``,
        ``_JOINT_NAMES``, ``_JOINT_LIMITS``, ...).

    Raises:
        RuntimeError: when ssik cannot be imported in this interpreter -- the
            message carries the install command and the gradient escape hatch
            (no silent fallback, matching the repo's philosophy).
    """
    mod = _MODULES.get(arm)
    if mod is None:
        if not available():
            raise RuntimeError(
                "ssik in-process backend unavailable (`import ssik` failed in this "
                f"interpreter, Python {sys.version_info.major}.{sys.version_info.minor}). "
                "Install it into this env (needs Python >= 3.11):\n"
                "    uv pip install --python <venv>\\Scripts\\python.exe \"ssik>=3.0,<4\"\n"
                "or set HUSKY_IK_BACKEND=gradient to use the PyBullet fallback."
            )
        # * The artifact folder holds plain .py modules generated by `ssik build`;
        # * putting it on sys.path is how they become importable (same trick the
        # * sidecar server uses).
        artifact_dir = config.get_ssik_artifact_dir()
        if artifact_dir not in sys.path:
            sys.path.insert(0, artifact_dir)
        module_name = config.SSIK_ARM_BUILD[arm][2]
        mod = import_module(module_name)
        # One-line breadcrumb so a log makes clear the sidecar was NOT used.
        print(f"[ssik-inprocess] loaded {module_name} from {artifact_dir}")
        _MODULES[arm] = mod
    return mod


def solve(
    arm: str,
    target_in_base,
    *,
    max_solutions: Optional[int] = None,
    q_seed=None,
    allow_rescue: bool = True,
) -> List[Tuple[np.ndarray, float]]:
    """Solve one arm's analytical IK in-process.

    Args:
        arm (str): "left" or "right".
        target_in_base: 4x4 tool0 target transform expressed in the arm's
            base-link frame, meters (array-like).
        max_solutions (Optional[int]): cap on returned branches (None = all).
        q_seed: optional 6-vector; when given, ssik orders branches
            nearest-to-seed first (trajectory-tracking mode).
        allow_rescue (bool): let ssik run its (slow, ~40x) numeric rescue when
            the exact solver finds nothing -- worth it for one-off endpoint
            solves, but turn it OFF in tracking loops: an unreachable waypoint
            should just fail fast (~1 ms), and rescued solutions are loose LM
            refinements that may sit on a different branch anyway.

    Returns:
        List[Tuple[np.ndarray, float]]: one ``(q6, fk_residual)`` pair per
        branch (joints in kinematic base->tool0 order, radians); empty list =
        pose unreachable.
    """
    module = _get_module(arm)
    sols = module.solve(
        np.asarray(target_in_base, dtype=float),
        max_solutions=max_solutions,
        q_seed=None if q_seed is None else np.asarray(q_seed, dtype=float),
        allow_rescue=allow_rescue,
    )
    return [(np.asarray(s.q, dtype=float), float(s.fk_residual)) for s in sols]


def joint_names(arm: str) -> List[str]:
    """The arm's 6 joint names in the solver's (kinematic) order.

    Args:
        arm (str): "left" or "right".

    Returns:
        List[str]: URDF joint names, base->tool0 order.
    """
    return list(_get_module(arm)._JOINT_NAMES)


def joint_limits(arm: str) -> List[Tuple[float, float]]:
    """The arm's joint limits in the solver's (kinematic) order.

    Args:
        arm (str): "left" or "right".

    Returns:
        List[Tuple[float, float]]: ``(lower, upper)`` per joint, radians.
    """
    return [(float(lo), float(hi)) for lo, hi in _get_module(arm)._JOINT_LIMITS]
